server:
  port: 9199

spring:
  #1.jdbc config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #druid:
    #old mysql driver
    #spring.datasource.driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    #jdbc-url: jdbc:mysql://192.168.96.218:3306/db_pclabdfs_115?characterEncoding=utf8&useOldAliasMetadataBehavior=true&allowMultiQueries=true&useSSL=false
    #username: root
    #password: Bywin123
    jdbc-url: jdbc:mysql://192.168.96.110:3306/pms_server?characterEncoding=utf8&useOldAliasMetadataBehavior=true&allowMultiQueries=true&useSSL=false
    username: bywin
    password: Bywin123
    #2.extend config
    initialSize: 3
    minIdle: 2
    maxActive: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis= 5000
    connection-timeout: 300000

  redis:
    host: 192.168.96.96
    port: 6379
    password: by321qaz
    database: 0
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 100
        # 最小空闲连接数
        min-idle: 20
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1
#自定义
#userLoginTimeOutMinutes: 600
#系统参数在redis名称前缀，未配置默认为shuyi_
#paraSetRedisPrefixName: shuyi_
#是否启用日志
logEnable: 1

workMode: 1
backend: 0
server_config: fate
#重定向模式
4a:
  redirect: true
  #开发阶段只拦截test的验证请求其他请求不进行拦截
  urlPattern: /*
  #前端cas单点登录服务校验地址
  cas:
    server:
      url: https://foura.bywin.cn:24016
      #单点登录服务校验排除的方式    CONTAINS:包含字符串        REGEX 正则表达式      EXACT 精确排除
      ignoreUrlPatternType: REGEX
      #单点登录服务校验排除的路径 #/system/logbackview|
      ignorePattern:  /4A/receiveTicket|/4A/validateTicket|/4A/getLoginUrl|/upload/*|/homepage/sysresourceset|/colmodel/readmodelrunjobinfo|/doc.html*|/swagger-resources/*|/v2/api-docs|/configuration/ui|/swagger-ui.html|/webjars/*|/excel/*|/ws/*|/*\.js
  #前端4A应用的服务地址
  app:
    server:
      url: http://localhost:9091/sy/index.html
  #4Acas的内网地址(在切掉外网访问时,通过内网访问cas,若有slb,则为slb内网地址)
  innetCasUrl:
  #服务先要接受ticket并且校验才能重定向到前端
  receive:
    ticket.url:  /api/4A/receiveTicket

olk:
  type: hetu
  driver: io.hetu.core.jdbc.OpenLooKengDriver
  url: jdbc:lk://192.168.96.80:8090/system
  connectionUrl: http://192.168.96.80:8090
  isEncryptPassword: false
  authType: none
  user: bywin
  passwd:

#权限认证模式 4a native local
auth:
  debug: 0
  mode: native
  class: cn.bywin.business.syslogin.LoginNativeMenu
  #class: cn.bywin.business.syslogin.Login4AMenu
  #class: cn.bywin.business.syslogin.LoginLocalMenu
#/system/logbackview|
urlIgnorePattern: user/register|/user/captcha|/homepage/sysresourceset|/colmodel/readmodelrunjobinfo|/doc.html*|/swagger-resources/*|/v2/api-docs|/configuration/ui|/doc.html*|/swagger-|/v3/|/webjars/*|/excel/*|/ws/*|/*\.js|/user|/dologin|/logout|/security/hasPermission

