server:
  #port: 9062
  servlet:
    context-path: /flserver
    #session:
      #timeout: 30s

logging: 
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
    org.springframework.web: INFO

  config: classpath:logback.xml

#endpoints in Spring Boot 2.0
#http://127.0.0.1:8008/actuator
management: 
  endpoints: 
    enabled-by-default: true
    web: 
      expose: /*
    
spring:
  profiles:
    active: dev
    #active: fz whga guizhoudm
  pid: 
    file: federalServer.pid
  jackson:
    time-zone: GMT+8
    serialization: 
      write-dates-as-timestamps: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  aop: 
    proxy-target-class: true

#mybaties config
# 设置 MyBatis mapper 的别名所在的包
mybatis:
  type-aliases-package: cn.bywin.business.bean
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-locations: classpath*:mapper/**/*.xml
  mappers: tk.mybatis.mapper.common.Mapper
  identity: MYSQL
